### ISSUE TITLE
Is riak Session thread safe?

### ISSUE THREAD

**Issue by jialic** [riaken/riaken-core#12]
Can I use the same riak Session in multiple goroutines?

**Comment by boj** [comment]
Sessions cannot be shared between threads due to how the messaging with the server occurs.  You will have to get a new session for each goroutine.

**Comment by jialic** [comment]
What about riak Client, is it thread safe?

**Comment by boj** [comment]
You should be able to pass it around without trouble.

**Comment by jialic** [comment]
Thanks @boj
