### ISSUE TITLE
Protobuf package new location

### ISSUE THREAD

**Issue by yvsong** [riaken/riaken-core#8]
Protobuf moved to github.com/golang/protobuf ?

**Comment by rdrm** [comment]
Having the same problem,
"package code.google.com/p/goprotobuf/proto: unable to detect version control system for code.google.com/ path"

pointing to the old path.

https://github.com/golang/protobuf

**Comment by phifty** [comment]
+1

**Comment by boj** [comment]
Fixed by #11
