### ISSUE TITLE
Counter incrementing and decrementing

### ISSUE THREAD

**Issue by joaonrb** [riaken/riaken-core#9]
If I do a 2 increments or decrements in a CrdtCounter the second value is going to override the first increment instead of accumulate.  Is there any special reason for this?

This is being a major headache for my project making me wrapping a huge structure over wrappers just to avoid one commit for each change in counter.

**Comment by boj** [comment]
@joaonrb Just an oversight.  Be happy to take a patch which corrects the behaviour.
